/** Mirrors `CollaborationActivityType` in prisma/schema.prisma. */
export enum CollaborationActivityType {
  CONVERSATION_CREATED = 'CONVERSATION_CREATED',
  PARTICIPANT_ADDED = 'PARTICIPANT_ADDED',
  PARTICIPANT_REMOVED = 'PARTICIPANT_REMOVED',
  MESSAGE_POSTED = 'MESSAGE_POSTED',
  ATTACHMENT_SHARED = 'ATTACHMENT_SHARED',
  ANNOUNCEMENT_PUBLISHED = 'ANNOUNCEMENT_PUBLISHED',
}
